name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker image tag
      id: vars
      run: echo "IMAGE_TAG=my-image-name:$(date +%s)" >> $GITHUB_ENV

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.IMAGE_TAG }}

    - name: Run the Docker container
      run: docker run -d --name my-container ${{ env.IMAGE_TAG }}

    - name: Healthcheck
      run: |
        sleep 30 # Wait for the container to start
        if [ "$(docker inspect --format='{{json .State.Health.Status}}' my-container)" != "\"healthy\"" ]; then
          echo "Container is not healthy"
          exit 1
        fi

    - name: Cleanup
      run: docker rm -f my-container
