name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Start FastAPI application
      run: |
        chmod +x start_app.sh
        ./start_app.sh
      env:
        PYTHONUNBUFFERED: '1'

    - name: Wait for the server to start
      run: sleep 5

    - name: Run tests
      env:
        PYTHONPATH: .
        FOLDER_ID: ${{ secrets.TEST_FOLDER_ID }}
        YANDEX_API_KEY: ${{ secrets.TEST_YANDEX_API_KEY }}
      run: pytest tests/
